language: node_js
node_js:
  - '0.10'

before_script:
  - npm link
  - npm install -g yo
  - mkdir tests && cd tests
  - yo marionette-sequelize --config.interactive=false
  - npm install
  - bower install

script: grunt build